version: "3.9"

services:
  server:
    build:
      context: "./"
      target: dev
    env_file: ./.env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - "4001:4001" # api
      - "3025:3025" # socket
    environment:
      - NODE_ENV=$NODE_ENV
      - DB_HOST=$DB_HOST
      # - DB_USER=$DB_USER
      # - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_LOCAL_PORT=$DB_LOCAL_PORT
      - SERVER_PORT=$SERVER_PORT
      - SOCKET_PORT=$SOCKET_PORT
      - CLIENT_URL=$CLIENT_URL
  mongo:
    image: mongo:6.0
    env_file: ./.env
    ports:
      - 27017:$DB_PORT
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=$DB_USER
    # - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data
