version: '3.7'

services:
  app: #should be server
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: server
    expose:
      - '4000'
    ports:
      - '4000:4000'
    links: 
      - mongodb
    command: npm run dev
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    volumes:
      - ./data:/data/db # here is a bug
    ports:
      - 27018:27017