version: "3.9"

services:
  server:
    build:
      context: './'
      target: dev
    volumes: 
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: development


    