name: football-chat.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: create env file
        run: |
          touch .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DB_LOCAL_PORT=${{ secrets.DB_LOCAL_PORT }} >> .env
          echo SERVER_PORT=${{ secrets.SERVER_PORT }} >> .env
          echo REDIS_URL=${{ secrets.REDIS_URL }} >> .env
          echo FOOTBALL_API_DATA_URL=${{ secrets.FOOTBALL_API_DATA_URL }} >> .env
          echo FOOTBALL_DATA_API_TOKEN=${{ secrets.FOOTBALL_DATA_API_TOKEN }} >> .env
          echo SOCKET_PORT=${{ secrets.SOCKET_PORT }} >> .env
          echo CLIENT_URL=${{ secrets.CLIENT_URL }} >> .env
      - run: |
          docker-compose -v
          docker-compose up
