name: football-chat.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - run: |
          echo $DB_LOCAL_PORT
          echo $DB_PORT
          docker-compose -v
          docker-compose up
