name: football-chat.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: create env file
        run: |
          touch .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
      - run: |
          docker-compose -v
          docker-compose up
