name: football-chat.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: "123456abcdef"
        NODE_ENV: ${{ secrets.NODE_ENV }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_LOCAL_PORT: ${{ secrets.DB_LOCAL_PORT }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        FOOTBALL_API_DATA_URL: ${{ secrets.FOOTBALL_API_DATA_URL }}
        FOOTBALL_DATA_API_TOKEN: ${{ secrets.FOOTBALL_DATA_API_TOKEN }}
        SOCKET_PORT: ${{ secrets.SOCKET_PORT }}
        CLIENT_URL: ${{ secrets.CLIENT_URL }}
        file_name: .env
      - run: |
          whoami
          docker-compose up
